[project]
name = "example-distributed-tracing"
version = "0.1.0"
description = "Repository to understand distributed tracing with examples"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.136.3",
    "opentelemetry-instrumentation-fastapi>=0.63b1",
    "uvicorn>=0.48.0",
]
